name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install shiv

      - name: Build pyz with Shiv
        run: |
          shiv -c mixy_dfu -o dist/mixy_dfu.pyz --preamble build_res/shiv_preamble.py mixy_dfu

      - name: Create GitHub Release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mixy_dfu.pyz
